import type { Task, Project, TaskType, TaskStatus } from "./types"

// タスクタイプのラベル
export const taskTypeLabels: Record<TaskType, string> = {
  meeting_designer: "Designer Meeting",
  meeting_developer: "Developer Meeting",
  proposal: "Proposal",
  quotation: "Quotation",
  deal_closed: "Deal Closed",
  bid_won: "Bid Won",
  deal_scale: "Deal Scale",
  site_support: "Site Support",
  delivery: "Delivery",
  complaint: "Complaint Handling",
  change: "Change Request",
  other: "Other",
  deal_date: "Deal Date",
  bid_date: "Bid Date",
  contract_date: "Contract Date",
}

// タスクステータスのラベル
export const taskStatusLabels: Record<TaskStatus, string> = {
  not_started: "Not Started",
  in_progress: "In Progress",
  completed: "Completed",
  delayed: "Delayed",
  on_hold: "On Hold",
  cancelled: "Cancelled",
}

export const sampleTasks: Task[] = [
  {
    id: "task-1",
    title: "Initial Designer Meeting",
    startDate: "2025-01-05",
    endDate: "2025-01-15",
    progress: 100,
    salesman: "Alex",
    client: "ABC Corporation",
    project: "ERP Implementation",
    priority: "high",
    taskType: "meeting_designer",
    amount: 0, // 面会は金額なし
    status: "completed",
    details: "Initial meeting with the lead designer to discuss project requirements",
  },
  {
    id: "task-2",
    title: "Project Proposal",
    startDate: "2025-01-16",
    endDate: "2025-01-30",
    progress: 80,
    salesman: "BillyLau",
    client: "ABC Corporation",
    project: "ERP Implementation",
    dependencies: ["task-1"],
    priority: "high",
    taskType: "proposal",
    amount: 0, // 提案段階では金額未定
    status: "in_progress",
    details: "Preparing detailed project proposal based on initial requirements",
  },
  {
    id: "task-3",
    title: "Quotation Preparation",
    startDate: "2025-02-01",
    endDate: "2025-02-28",
    progress: 60,
    salesman: "Grace",
    client: "ABC Corporation",
    project: "ERP Implementation",
    dependencies: ["task-2"],
    priority: "medium",
    taskType: "quotation",
    amount: 500000, // 見積金額
    status: "in_progress",
    details: "Preparing detailed cost estimation for the project",
  },
  {
    id: "task-4",
    title: "Deal Closed",
    startDate: "2025-02-01",
    endDate: "2025-03-15",
    progress: 40,
    salesman: "Ivan",
    client: "ABC Corporation",
    project: "ERP Implementation",
    dependencies: ["task-3"],
    priority: "medium",
    taskType: "deal_closed",
    amount: 450000, // 成約金額
    status: "in_progress",
    details: "Final negotiations and contract signing",
  },
  {
    id: "task-5",
    title: "Developer Meeting",
    startDate: "2025-01-10",
    endDate: "2025-01-25",
    progress: 100,
    salesman: "Vincent",
    client: "XYZ Inc.",
    project: "Product Launch",
    priority: "high",
    taskType: "meeting_developer",
    amount: 0,
    status: "completed",
    details: "Initial meeting with development team to discuss technical requirements",
  },
  {
    id: "task-6",
    title: "Product Proposal",
    startDate: "2025-01-26",
    endDate: "2025-02-15",
    progress: 75,
    salesman: "Anson",
    client: "XYZ Inc.",
    project: "Product Launch",
    dependencies: ["task-5"],
    priority: "high",
    taskType: "proposal",
    amount: 0,
    status: "in_progress",
    details: "Creating product proposal with features and timeline",
  },
  {
    id: "task-7",
    title: "Deal Scale Finalization",
    startDate: "2025-02-16",
    endDate: "2025-03-05",
    progress: 30,
    salesman: "BillyLi",
    client: "XYZ Inc.",
    project: "Product Launch",
    dependencies: ["task-6"],
    priority: "medium",
    taskType: "deal_scale",
    amount: 750000, // 商談スケール金額
    status: "in_progress",
    details: "Finalizing project scope, timeline and budget",
  },
  {
    id: "task-8",
    title: "Site Support Planning",
    startDate: "2025-01-15",
    endDate: "2025-02-05",
    progress: 90,
    salesman: "Kami",
    client: "123 Systems",
    project: "Cloud Migration",
    priority: "high",
    taskType: "site_support",
    amount: 120000,
    status: "in_progress",
    details: "Planning for on-site support during implementation",
  },
  {
    id: "task-9",
    title: "Delivery Preparation",
    startDate: "2025-02-06",
    endDate: "2025-03-10",
    progress: 50,
    salesman: "Ricky",
    client: "123 Systems",
    project: "Cloud Migration",
    dependencies: ["task-8"],
    priority: "high",
    taskType: "delivery",
    amount: 300000,
    status: "in_progress",
    details: "Preparing for final delivery of the migration solution",
  },
  {
    id: "task-10",
    title: "Change Request Handling",
    startDate: "2025-03-11",
    endDate: "2025-03-25",
    progress: 20,
    salesman: "Ada",
    client: "123 Systems",
    project: "Cloud Migration",
    dependencies: ["task-9"],
    priority: "medium",
    taskType: "change",
    amount: 80000, // 変更対応の追加金額
    status: "in_progress",
    details: "Processing client change requests for additional features",
  },
  // 新しいサンプルタスクを追加
  {
    id: "task-11",
    title: "Contract Signing Date",
    startDate: "2025-01-31",
    endDate: "2025-01-31",
    progress: 100,
    salesman: "Ivan",
    client: "ABC Corporation",
    project: "ERP Implementation",
    priority: "high",
    taskType: "contract_date",
    amount: 0,
    status: "completed",
    details: "Contract officially signed with the client",
  },
  {
    id: "task-12",
    title: "Deal Confirmation Date",
    startDate: "2025-02-15",
    endDate: "2025-02-15",
    progress: 100,
    salesman: "BillyLi",
    client: "XYZ Inc.",
    project: "Product Launch",
    priority: "high",
    taskType: "deal_date",
    amount: 0,
    status: "completed",
    details: "Deal officially confirmed with the client",
  },
  {
    id: "task-13",
    title: "Bid Win Date",
    startDate: "2025-01-14",
    endDate: "2025-01-14",
    progress: 100,
    salesman: "Kami",
    client: "123 Systems",
    project: "Cloud Migration",
    priority: "high",
    taskType: "bid_date",
    amount: 0,
    status: "completed",
    details: "Bid officially won for the project",
  },
  {
    id: "task-14",
    title: "Long-term System Integration",
    startDate: "2025-04-01",
    endDate: "2025-12-15",
    progress: 10,
    salesman: "BillyLau",
    client: "Global Tech",
    project: "Digital Transformation",
    priority: "high",
    taskType: "site_support",
    amount: 850000,
    status: "in_progress",
    details: "Long-term system integration project spanning multiple quarters",
  },
  {
    id: "task-15",
    title: "Platform Development",
    startDate: "2025-05-10",
    endDate: "2025-11-30",
    progress: 15,
    salesman: "Vincent",
    client: "Global Tech",
    project: "Digital Transformation",
    dependencies: ["task-14"],
    priority: "high",
    taskType: "delivery",
    amount: 650000,
    status: "in_progress",
    details: "Development of the core platform components",
  },
  {
    id: "task-16",
    title: "Contract Signing Date",
    startDate: "2025-03-15",
    endDate: "2025-03-15",
    progress: 100,
    salesman: "Ivan",
    client: "Global Tech",
    project: "Digital Transformation",
    priority: "high",
    taskType: "contract_date",
    amount: 0,
    status: "completed",
    details: "Contract officially signed with Global Tech",
  },
  {
    id: "task-17",
    title: "Infrastructure Planning",
    startDate: "2025-06-01",
    endDate: "2025-12-31",
    progress: 5,
    salesman: "Alex",
    client: "Future Corp",
    project: "Next-Gen Infrastructure",
    priority: "medium",
    taskType: "meeting_designer",
    amount: 300000,
    status: "in_progress",
    details: "Initial planning phase for the next-generation infrastructure",
  },
  {
    id: "task-18",
    title: "Preliminary Design",
    startDate: "2026-01-15",
    endDate: "2026-06-30",
    progress: 0,
    salesman: "Grace",
    client: "Future Corp",
    project: "Next-Gen Infrastructure",
    dependencies: ["task-17"],
    priority: "medium",
    taskType: "proposal",
    amount: 450000,
    status: "not_started",
    details: "Preliminary design work for the infrastructure components",
  },
  {
    id: "task-19",
    title: "Implementation Phase 1",
    startDate: "2026-07-01",
    endDate: "2027-01-31",
    progress: 0,
    salesman: "Anson",
    client: "Future Corp",
    project: "Next-Gen Infrastructure",
    dependencies: ["task-18"],
    priority: "high",
    taskType: "delivery",
    amount: 1200000,
    status: "not_started",
    details: "First phase of implementation for the next-generation infrastructure",
  },
  {
    id: "task-20",
    title: "Implementation Phase 2",
    startDate: "2027-02-01",
    endDate: "2027-06-30",
    progress: 0,
    salesman: "Ricky",
    client: "Future Corp",
    project: "Next-Gen Infrastructure",
    dependencies: ["task-19"],
    priority: "high",
    taskType: "delivery",
    amount: 950000,
    status: "not_started",
    details: "Second phase of implementation for the next-generation infrastructure",
  },
  {
    id: "task-21",
    title: "Contract Signing Date",
    startDate: "2025-05-20",
    endDate: "2025-05-20",
    progress: 100,
    salesman: "BillyLi",
    client: "Future Corp",
    project: "Next-Gen Infrastructure",
    priority: "high",
    taskType: "contract_date",
    amount: 0,
    status: "completed",
    details: "Contract officially signed with Future Corp",
  },
]

// プロジェクトデータの作成
export const sampleProjects: Project[] = [
  {
    id: "project-1",
    name: "ERP Implementation",
    client: "ABC Corporation",
    totalAmount: 950000,
    startDate: "2025-01-05",
    endDate: "2025-03-15",
    tasks: sampleTasks.filter((task) => task.project === "ERP Implementation"),
    amountProgress: 47,
    salesmen: ["Alex", "BillyLau", "Grace", "Ivan"]
  },
  {
    id: "project-2",
    name: "Product Launch",
    client: "XYZ Inc.",
    totalAmount: 750000,
    startDate: "2025-01-10",
    endDate: "2025-03-05",
    tasks: sampleTasks.filter((task) => task.project === "Product Launch"),
    amountProgress: 30,
    salesmen: ["Vincent", "Anson", "BillyLi"]
  },
  {
    id: "project-3",
    name: "Cloud Migration",
    client: "123 Systems",
    totalAmount: 500000,
    startDate: "2025-01-15",
    endDate: "2025-03-25",
    tasks: sampleTasks.filter((task) => task.project === "Cloud Migration"),
    amountProgress: 65,
    salesmen: ["Kami", "Ricky", "Ada"]
  },
  {
    id: "project-4",
    name: "Digital Transformation",
    client: "Global Tech",
    totalAmount: 1500000,
    startDate: "2025-03-15",
    endDate: "2025-12-15",
    tasks: [],
    amountProgress: 12,
    salesmen: ["BillyLau", "Vincent", "Ivan"]
  },
  {
    id: "project-5",
    name: "Next-Gen Infrastructure",
    client: "Future Corp",
    totalAmount: 2900000,
    startDate: "2025-05-20",
    endDate: "2027-06-30",
    tasks: [],
    amountProgress: 3,
    salesmen: ["Alex", "Grace", "Anson", "Ricky"]
  },
]

// プロジェクトごとのタスクに金額進捗率を追加
sampleProjects.forEach((project) => {
  project.tasks = sampleTasks.filter((task) => task.project === project.name)
  project.tasks.forEach((task) => {
    if (task.amount && task.amount > 0) {
      task.amountProgress = (task.progress / 100) * (task.amount / project.totalAmount) * 100
      task.totalAmount = project.totalAmount
    }
  })
})
